AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bench/**/*'
    - 'lib/anycable/rpc/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - 'Gemfile'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/**/*_test.rb'
    - 'lib/anycablebility/dummy/**/*'

Style/StringLiterals: 
  Enabled: true
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
